library("GillespieSSA")

library("deSolve")

simName<-"SEIAR model Teismann"

rates<-c("c*(beta_p*I_p_w+beta_m*I_m_w+beta_A*A_w)*S_w/(S_w+E_w+B_w+A_w+I_p_w+I_m_w+J_w+H_w+F_w+Q_m_w+Q_J_w+R_w)",
         "gamma",
         "mu_E*E_w",
         "(1-phi)*mu_1*I_p_w",
         "mu_2*A_w",
         "phi*mu_1*I_p_w",
         "theta*mu_2*I_m_w",
         "(1-theta)*mu_2*I_m_w",
         "lambda*I_m_w",
         "lambda*J_w",
         "mu_2*Q_m_w",
         "mu_J*J_w",
         "mu_J*Q_J_w",
         "rho*mu_H*H_w",
         "(1-rho)*mu_H*H_w", 
         "kappa*E_w",
         "kappa*A_w",
         "kappa*I_p_w",
         "c*(beta_p*I_p_n+beta_m*I_m_n+beta_A*A_n)*S_n/(S_n+E_n+B_n+A_n+I_p_n+I_m_n+J_n+H_n+F_n+Q_m_n+Q_J_n+R_n)",
         "mu_E*E_n",
         "(1-phi)*mu_1*I_p_n",
         "mu_2*A_n",
         "phi*mu_1*I_p_n",
         "theta*mu_2*I_m_n",
         "(1-theta)*mu_2*I_m_n",
         "lambda*I_m_n",
         "lambda*J_n",
         "mu_2*Q_m_n",
         "mu_J*J_n",
         "mu_J*Q_J_n",
         "rho*mu_H*H_n",
         "(1-rho)*mu_H*H_n", 
         "kappa*E_n",
         "kappa*A_n",
         "kappa*I_p_n",
         "c*(beta_p*I_p_c+beta_m*I_m_c+beta_A*A_c)*S_c/(S_c+E_c+B_c+A_c+I_p_c+I_m_c+J_c+H_c+F_c+Q_m_c+Q_J_c+R_c)",
         "mu_E*E_c",
         "(1-phi)*mu_1*I_p_c",
         "mu_2*A_c",
         "phi*mu_1*I_p_c",
         "theta*mu_2*I_m_c",
         "(1-theta)*mu_2*I_m_c",
         "lambda*I_m_c",
         "lambda*J_c",
         "mu_2*Q_m_c",
         "mu_J*J_c",
         "mu_J*Q_J_c",
         "rho*mu_H*H_c",
         "(1-rho)*mu_H*H_c", 
         "kappa*E_c",
         "kappa*A_c",
         "kappa*I_p_c",
         "c*(beta_p*I_p_e+beta_m*I_m_e+beta_A*A_e)*S_e/(S_e+E_e+B_e+A_e+I_p_e+I_m_e+J_e+H_e+F_e+Q_m_e+Q_J_e+R_e)",
         "mu_E*E_e",
         "(1-phi)*mu_1*I_p_e",
         "mu_2*A_e",
         "phi*mu_1*I_p_e",
         "theta*mu_2*I_m_e",
         "(1-theta)*mu_2*I_m_e",
         "lambda*I_m_e",
         "lambda*J_e",
         "mu_2*Q_m_e",
         "mu_J*J_e",
         "mu_J*Q_J_e",
         "rho*mu_H*H_e",
         "(1-rho)*mu_H*H_e", 
         "kappa*E_e",
         "kappa*A_e",
         "kappa*I_p_e"
         )

nu<-matrix(c(-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             +1,+1,-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,-1, 0, 0,
             0, 0, 0, 0,+1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             0,+1, 0,+1,-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,-1, 0,
             0,+1,-1,-1, 0,-1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,-1,
             0, 0, 0, 0, 0,+1,-1,-1,-1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0,+1, 0, 0,-1, 0,-1, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0,+1, 0, 0, 0, 0, 0,-1,-1, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,+1, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,+1, 0,-1, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0, 0,+1,+1, 0,-1, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,+1,+1,+1, 0, 0, 0, 0),
           nrow=48, byrow=TRUE)




